### ISSUE TITLE
listItem parse start error Invalid argument(s): The source must not be null

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [jarontai/html2md#13]
I'm getting this error all of a sudden when parsing HTML. I'm still trying to analyze the source code to see why, but maybe the library can account for the error? I'm attaching a link to a sample project. all you have to do is run it in debug mode and enable the breakpoints to see the error. It seems to render fine, I believe, but I can't say for certain that something isn't left out/
https://github.com/ThinkDigitalSoftware/html2markdown_error_example

**Comment by jarontai** [comment]
Thank you for the report. v0.3.3 is out, this should be fixed.

**Comment by ThinkDigitalSoftware** [comment]
Thank you!
