### ISSUE TITLE
Tables are not being converted properly

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [jarontai/html2md#14]
This is slightly complex, but I've narrowed it down to this package.
I'm using this lib to convert html to markdown and then render it in Flutter.
The original Markdown source is here. https://github.com/flutterchina/dio/blob/master/README.md
for comparison.
This is the actual HTML page that's being passed to html2md https://pub.dev/packages/dio
 You can see the table in the screenshot
<img width="854" alt="Screen Shot 2019-11-13 at 10 39 00 AM" src="https://user-images.githubusercontent.com/23037821/68793364-ebdbb580-0601-11ea-839c-807a79d820d2.png">

But when it's rendered, it shows like this.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-13 at 10 36 09](https://user-images.githubusercontent.com/23037821/68793393-feee8580-0601-11ea-889d-007917014e54.png)

To make a long story short, the table should be rendered like this, 
https://github.com/flutterchina/dio/blob/master/README.md

[Copy of markdown rendered by html2md](https://gist.github.com/ThinkDigitalSoftware/b7ed337b907b7779848a10f632ed766d)

**Comment by jarontai** [comment]
Thank you for the report! This problem should caused by the wrong replacement of thead and tbody.

**Comment by jarontai** [comment]
Version 0.5.1 published. I add a test for your table source and fix the thead/tbody problem.

**Comment by ThinkDigitalSoftware** [comment]
That was quick, thank you!
