### ISSUE TITLE
output has \- or \* instead of - or *

### ISSUE THREAD

**Issue by csells** [jarontai/html2md#15]
I'm not sure why that is, but it seems deliberate. How do I turn that off?

**Comment by jarontai** [comment]
That's odd. Do you got any examples?

**Comment by csells** [comment]
import 'package:html2md/html2md.dart' as html2md;

void main() {
  final html = '---';
  final md = html2md.convert(html);
  print(md); // \-\-\-
}

**Comment by jarontai** [comment]
All the markdown characters would be escaped before processing: https://github.com/domchristie/turndown#escaping-markdown-characters

if your input dose not start with hyphen, that should be ok.

**Comment by csells** [comment]
Valid HTML is not going to have Markdown characters escaped. For sample, this causes the same problem:

```dart
import 'package:html2md/html2md.dart' as html2md;

void main() {
  final html = '<body><p>---</p></body>';
  final md = html2md.convert(html);
  print(md); // \-\-\-
}
```

**Comment by csells** [comment]
Although I think you're right in general -- the HTML source I'm using may be mixing MD constructs in with the HTML. I'll take a look at that.
