### ISSUE TITLE
Custom Text Size 

### ISSUE THREAD

**Issue by PhyoeKo** [jarontai/html2md#20]
How can I set custom text site in HTML data?

**Comment by jarontai** [comment]
Maybe you should try building a custom rule to hadle this. 

Build a function to filter your target tags first, then build the replacement function to produce the text size html. 

If your html is complex, you should family with [html](https://pub.dev/packages/html). Html2md's Node class is just a wrapper of   [html](https://pub.dev/packages/html)'s dom node.

Custom rule example: [custom-rules](https://github.com/jarontai/html2md#custom-rules)
