### ISSUE TITLE
Ignore Markdown on String 

### ISSUE THREAD

**Issue by jhecksonSa** [jarontai/html2md#26]
Hi, I am trying to convert HTML with markdown together
String example: ```## Heading level 2 <p>html p<p>```

![ApPpV9.png](https://a.imagem.app/ApPpV9.png)

**Comment by jarontai** [comment]
Hi [jhecksonSa](https://github.com/jhecksonSa), I'm afraid this may beyond the scope of html2d, maybe you can preprocess the html string first.

**Comment by jarontai** [comment]
If the markdown string is wrapped by a tag, then you can put them in the `ignore` [config](https://github.com/jarontai/html2md#config) to ignore them. And you can even write custom [rule](https://github.com/jarontai/html2md#custom-rules) to customize the process of the tag.

**Comment by jhecksonSa** [comment]
Thanks for all, but i don't think this package's going to solve my problem then, since the text that I need to filter have markdown inside and out of the html tags.
