### ISSUE TITLE
[proposal] `convert` accept `dom.Node` parameter

### ISSUE THREAD

**Issue by lindeer** [jarontai/html2md#29]
add another convert function like:
```
String from(
  String Dom.Node, {
  String? rootTag,
  String? imageBaseUrl,
  Map<String, String>? styleOptions,
  List<String>? ignore,
  List<Rule>? rules,
}) 
```
In some cases, we have to modify html DOM tree before we pass it to `html2md`, the new function could avoid extra parsing operations.

**Comment by jarontai** [comment]
I don't have much time to add new features, can you provide some example code anyway

**Comment by lindeer** [comment]
```dart
  import 'package:html/parser.dart' as parser;

  final doc = parser.parse(htmlContent);
  final body = doc.body;
  // a lot of operations to body
  final markdown = html2md.convert(body)
```

**Comment by jarontai** [comment]
can't you just use the outerHtml? In my opinion, using string as input can keeps html2md from directly depending on any external library.

 ```dart
import 'package:html/parser.dart' as parser;
import "package:html2md/html2md.dart" as html2md;

final doc = parser.parse("htmlContent");
final body = doc.body;
// a lot of operations to body
final bodyHtml = body?.outerHtml;
final markdown = html2md.convert(bodyHtml!);
 ```

**Comment by lindeer** [comment]
@jarontai yes, it is possible, but my proopsal is directly accepting dom object not string, so that the function could **avoid extra parsing operations.**, your implement actually use dom internally:
```
  factory Node.root(String html, {String? rootTag}) {
    var doc = parse(html);
    dom.Element? root;
    if (rootTag != null && rootTag.isNotEmpty) {
      root = doc.getElementsByTagName(rootTag).first;
    }
    root ??= doc.getElementsByTagName('html').first;
    return Node(util.prepareRoot(root));
  }
```

**Comment by lindeer** [comment]
hey @jarontai , I add a [PR](https://github.com/jarontai/html2md/pull/30) for my idea, you could have a review :smile:

**Comment by jarontai** [comment]
Hi @lindeer, thank you for the pr. I prefer to let the convert function accept dynamic input instead of adding a new entry function. Here is my pr, please take a look: https://github.com/jarontai/html2md/pull/31

**Comment by jarontai** [comment]
version 1.3.0 published
