### ISSUE TITLE
text-align did not convert

### ISSUE THREAD

**Issue by NitiLTechscape** [jarontai/html2md#40]
I have this html
`<h1 style="margin-left:0px;text-align:center;">Personal Data Protection Policy&nbsp;<br>of&nbsp;<br>Public Company Limited and&nbsp;<br>Group of companies</h1>`
it should be like this
<img width="492" alt="Screenshot 2566-09-26 at 17 25 41" src="https://github.com/jarontai/html2md/assets/116702363/6faebd4b-df50-4857-8051-b208a410ee5f">
but the result is
<img width="506" alt="Screenshot 2566-09-26 at 17 25 58" src="https://github.com/jarontai/html2md/assets/116702363/76ac5f8c-6009-4a2d-9d53-39e06fdb02cc">

**Comment by jarontai** [comment]
I‘m afraid markdown has no native support for text align.

https://stackoverflow.com/questions/53419155/how-to-center-text-with-markdown
