### ISSUE TITLE
Links for TOC - Spaces are replaced with _ insted of -

### ISSUE THREAD

**Issue by jnerlich** [jarontai/html2md#44]
Hi, 

after converting a wikipage to markdown using html2md the links of the table of content do not work for me because the spaces are being replaced with _ (underscores) instead of - (hyphens). 
Is there a way to change this?

BR, Jennifer

**Comment by jarontai** [comment]
I don't think spaces in link will be replaced, can you provide an example?

**Comment by jnerlich** [comment]
I'm converting this wikipage: https://wiki.eclipse.org/Version_Numbering and in the links generated for the table of content the spaces are being replaced by underscores.
Example wikipage: 1.1 When to change the major segment
After conversion:   *   [1.1 When to change the major segment](#When_to_change_the_major_segment)

**Comment by jarontai** [comment]
I guess it's because the original href uses underscores.

![image](https://github.com/jarontai/html2md/assets/5214514/19dc18ec-7fc4-45a4-9360-0dab2fc2f9c5)

**Comment by jnerlich** [comment]
Thanks.
