### ISSUE TITLE
Fenced code blocks with multiple children (spans from highligters) not converted

### ISSUE THREAD

**Issue by sanzoghenzo** [jarontai/html2md#45]
Hi, first of all many thanks for your work, I'm using this library in my android app and it's working really well!

Unfortunately, a user of the app opened [an issue](https://github.com/sanzoghenzo/markdownr/issues/67) because some code blocks in a webpage don't get converted: only the first line is displayed.

That specific webpage was created with Jekyll from a markdown source, so I'm expecting that many other websites could be affected.

This is an excerpt from the page:

```html
<div class="language-python highlighter-rouge">
  <div class="highlight">
<pre class="highlight"><code><span class="c1">#! /usr/bin/env python3
</span>
<span class="kn">import</span> <span class="nn">tika</span>
<span class="kn">from</span> <span class="nn">tika</span> <span class="kn">import</span> <span class="n">parser</span>

<span class="n">fileIn</span> <span class="o">=</span> <span class="s">"berk011veel01_01.epub"</span>
<span class="n">fileOut</span> <span class="o">=</span> <span class="s">"berk011veel01_01.txt"</span>

<span class="n">parsed</span> <span class="o">=</span> <span class="n">parser</span><span class="p">.</span><span class="n">from_file</span><span class="p">(</span><span class="n">fileIn</span><span class="p">)</span>
<span class="n">content</span> <span class="o">=</span> <span class="n">parsed</span><span class="p">[</span><span class="s">"content"</span><span class="p">]</span>

<span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="n">fileOut</span><span class="p">,</span> <span class="s">'w'</span><span class="p">,</span> <span class="n">encoding</span><span class="o">=</span><span class="s">'utf-8'</span><span class="p">)</span> <span class="k">as</span> <span class="n">fout</span><span class="p">:</span>
    <span class="n">fout</span><span class="p">.</span><span class="n">write</span><span class="p">(</span><span class="n">content</span><span class="p">)</span>
</code></pre>
  </div>
</div>
```

The issue is [at this line](https://github.com/jarontai/html2md/blob/8d877fc1acfc6587a23459d833192f264b7ea410/lib/src/rules.dart#L236): only the first child of the `code` tag is read.

**Comment by sanzoghenzo** [comment]
I tried with a custom rule, and replacing the incriminated line with `childNodes().map((e) => e.textContent).join()` renders all the code.

I'm not sure how to solve the language identification, that info appears two `div`s up instead of in the first children. I don't know if it a standard of some kind or a particular case of this website (it uses jekyll and a bootstrap theme).

**Comment by jarontai** [comment]
Hi sanzoghenzo, I don't think that's a standard for code blocks.

In the custom rule, you can get the parents or maybe any elements you want, by using the dom api. 
For example(may not work): `node.asElement()?.parent?.parent?.classes;`
