### ISSUE TITLE
Exception with blockquote

### ISSUE THREAD

**Issue by tsdevelopment** [jarontai/html2md#6]
Whenever I use the `blockquote` tag I get an exception:

` Another exception was thrown: 'package:flutter/src/widgets/container.dart': Failed assertion: line 59 pos 15: 'decoration != null': is not true.`

Example code:
`String markdown = html2md.convert('<blockquote>Lorem ipsum...</blockquote>');`

**Comment by jarontai** [comment]
`String markdown = html2md.convert('<blockquote>Lorem ipsum...</blockquote>');
`

I can run the example code on my machine. I think the exception was thrown by your flutter code.
