### ISSUE TITLE
content in <script> tags are not filtered out

### ISSUE THREAD

**Issue by atn832** [jarontai/html2md#8]
This snippet:

```
final html = """
<!DOCTYPE html>
<head>
	<script>
    console.log("test");
	</script>
</head>
<body>
Hello
</body>
""";
final md = html2md.convert(html);
print(md);
```

prints out a string that contains 'console.log("test");'. I would have expected only Hello to be included.

**Comment by jarontai** [comment]
Version 0.3.0 is out, you can exclude elements with the new `ignore` parameter.

**Comment by atn832** [comment]
Thank you!
