### ISSUE TITLE
Exception when using inside ListView(Builder)

### ISSUE THREAD

**Issue by jurrdb** [jarontai/html2md#9]
When this widget is used inside of a ListView or a ListViewBuilder, the following exception is thrown:
`Vertical viewport was given unbounded height.`
Some more info:
`Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter ( 9925): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter ( 9925): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter ( 9925): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter ( 9925): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter ( 9925): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter ( 9925): the height of the viewport to the sum of the heights of its children.`

Using shrinkWrap, or wrapping the HTML view widget inside a Container, Flexible, or Expanded does not help.

**Comment by jarontai** [comment]
I haven't test with flutter, so I can't confirm the compatibility with flutter. I will check this when I have time.

**Comment by ueman** [comment]
html2md itself does work with Flutter. You probably used [Flutter Markdown](https://pub.dev/packages/flutter_markdown) and its Markdown widget. Inside a ListView you have to use the MarkdownBody widget. If you look at the Markdown widgets source code you can see it is already placed inside a ListView. 

So for example you have to do it like this:
```
ListView(
    children: <Widget>[
        // other widgets
       MarkdownBody(data: markdownString),
       // more widgets
   ]
);
```

**Comment by jarontai** [comment]
Html2md is not a flutter widget, but you can use it to convert html source to markdown, then send to flutter_markdown widget.
